load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

kt_asset_test(
    name = "chatmessageasset_test",
    srcs = ["ChatMessageAssetTest.kt"],
    test_class = "com.intuit.playerui.android.reference.assets.chatmessageasset.ChatMessageAssetTest",
)
