load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/string-resolver",
    dependencies = [
        "//core/binding:@player-ui/binding",
        "//core/data:@player-ui/data",
        "//core/types:@player-ui/types",
        "@npm//timm",
    ],
)
