load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/auto-scroll-manager-plugin-react",
    dependencies = [
        "@npm//smooth-scroll-into-view-if-needed",
    ],
    peer_dependencies = [
        "//react/player:@player-ui/react",
    ],
)
