disabled_rules:
    - unused_optional_binding
    - unused_setter_value
type_name:
    excluded:
        - T
line_length:
    error: 160
    ignores_comments: true
function_body_length: 50
identifier_name:
    excluded:
        - id
        - file_input
        - text_input
        - check_box
        - drop_down
        - radio_button
        - search_input
included:
    - ios
    - plugins
