codecov:
  require_ci_to_pass: no
# Post comment if there are changes in bundle size increases more than 1Kb
comment:
     require_bundle_changes: "bundle_increase"
     bundle_change_threshold: "1Kb"