packages:
  - "core/*"
  - "react/*"
  - "plugins/*/*"
  - "tools/*/*"
  - "tools/*"
  - "docs/*"

strictDepBuilds: true
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - "@player-tools/*"
