packages:
  - "core/*"
  - "react/*"
  - "plugins/*/*"
  - "tools/*/*"
  - "tools/*"
  - "docs/*"

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - core-js-pure
  - yarn

strictDepBuilds: true
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - "@player-tools/*"
