load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/asset-provider-plugin-react",
    dependencies = [
        "//react/asset:@player-ui/react-asset",
        "//react/subscribe:@player-ui/react-subscribe",
    ],
    peer_dependencies = [
        "//react/player:@player-ui/react",
    ],
)
