load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/react-shared-constants",
    entry = "src/index.tsx",
    dependencies = [
        "//react/utils:@player-ui/react-utils",
    ],
    peer_dependencies = [
    ],
)
