# load("//plugins/reference-assets/android:build.bzl", "kt_asset_test")

# kt_asset_test(
#     name = "info_test",
#     srcs = ["InfoTest.kt"],
#     test_class = "com.intuit.player.android.reference.assets.info.InfoTest"
# )
