cc_import(
    name = "libjsi",
    shared_library = ":libjsi.so",
    visibility = ["//visibility:public"],
)

cc_import(
    name = "libfbjni",
    shared_library = ":libfbjni.so",
    visibility = ["//visibility:public"],
)

cc_import(
    name = "libc++_shared",
    shared_library = ":libc++_shared.so",
    visibility = ["//visibility:public"],
)