load("//jvm:defs.bzl", "kt_player_module")
load(":deps.bzl", "main_deps")

kt_player_module(
    name = "utils",
    main_deps = main_deps,
    main_resources = ["//core/make-flow:MakeFlow_Bundles"],
    test_package = "com.intuit.playerui.utils",
)
