load("//android/player:build.bzl", "kt_player_test")

kt_player_test(
    name = "extensions-tests",
    srcs = [
        "CoroutineTestDispatcherExtension.kt",
        "IntoKtTest.kt"
    ],
)

exports_files(["CoroutineTestDispatcherExtension.kt"])
