load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

kt_asset_test(
    name = "collection_test",
    srcs = ["CollectionTest.kt"],
    test_class = "com.intuit.playerui.android.reference.assets.collection.CollectionTest",
)
