load("//android/player:build.bzl", "kt_player_test")

kt_player_test(
    name = "logger-tests",
    srcs = [
        "AndroidLoggerTest.kt"
    ],
    associates = ["//android/player:player-associates"]
)
