# load("//plugins:build.bzl", "kt_player_plugin")
# load(":deps.bzl", "main_deps", "main_exports", "main_resources")

# kt_player_plugin(
#     name = "external-action",
#     main_deps = main_deps,
#     main_exports = main_exports,
#     main_resources = main_resources,
#     # TODO: Reformat package
#     test_package = "com.intuit.player.plugins.externalAction",
# )
