load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/flow",
    dependencies = [
        "//core/logger:@player-ui/logger",
        "//core/types:@player-ui/types",
        "@npm//tapable",
        "@npm//p-defer",
    ],
)
