# load("//plugins/reference-assets/android:build.bzl", "kt_asset_test")

# kt_asset_test(
#     name = "text_test",
#     srcs = ["TextTest.kt"],
#     test_class = "com.intuit.player.android.reference.assets.text.TextTest"
# )
