load("//tools/ios:util.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "FancyPlugin",
    resources = [
      "//plugins/fancy/core:core_native_bundle"
    ],
    deps = [
        "//ios/swiftui:PlayerUISwiftUI"
    ]
)