load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/constants",
    peer_dependencies = [
        "//core/binding:@player-ui/binding",
        "//core/data:@player-ui/data",
    ],
)
