load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/data",
    dependencies = [
        "//core/binding:@player-ui/binding",
        "@npm//@types/dlv",
        "@npm//dlv",
        "@npm//tapable-ts",
        "@npm//timm",
    ],
)
