# load("//plugins/reference-assets/android:build.bzl", "kt_asset_test")

# kt_asset_test(
#     name = "collection_test",
#     srcs = ["CollectionTest.kt"],
#     test_class = "com.intuit.player.android.reference.assets.collection.CollectionTest"
# )
