import type { Node, ViewController, ViewInstance } from "@player-ui/player";

export type AsyncNodeInfo = {
  /** The async node */
  asyncNode: Node.Async;
  /** All nodes that need to be updated when the async content changes. This could be the async node itself, or a node that created it (i.e. an asset node that transformed into an async node). */
  updateNodes: Set<Node.Node>;
  /** The resolved content for this async node */
  resolvedContent?: Node.Node;
};

/** Object type for storing data related to a single `apply` of the `AsyncNodePluginPlugin`
 * This object should be setup once per ViewInstance to keep any cached info just for that view to avoid conflicts of shared async node ids across different view states.
 */
export type AsyncPluginContext = {
  /** The view instance this context is attached to. */
  view: ViewInstance;
  /** The view controller this context is attached to. */
  viewController: ViewController;
  /** Set of async node ids that are currently being managed by an incomplete promise. */
  inProgressNodes: Set<string>;
  /** Map of async node ids to related info for that node. */
  asyncNodeCache: Map<string, AsyncNodeInfo>;
  /** Maps asset ids to its original node. Used to then search for what if could be generated by. */
  assetIdCache: Map<string, Node.Node>;
  /** Maps nodes to the async id that generated them. */
  generatedByMap: Map<Node.Node, string>;
  /** Map to track the original parent of nodes that were flattened into another. This is needed to track which async nodes actually generated these nodes. */
  originalParentMap: Map<Node.Node, Node.Node>;
};
