import { describe, test, expect, vi, beforeEach } from "vitest";
import * as core from "@auto-it/core";

// Capture every execPromise call (git/unzip/gh/rm) instead of running them.
const execPromise = vi.spyOn(core, "execPromise");

import SpmReleasePlugin, {
  buildReleaseNotes,
  buildTagAnnotation,
  branchForVersion,
  isPrerelease,
  sourceReference,
} from "..";

const OPTIONS = {
  targetRepoUrl: "git@github.com:player-ui/playerui-swift-package.git",
  targetRepo: "player-ui/playerui-swift-package",
  zipPath: "./dist/PlayerUI_SPM.zip",
};

const RELEASE_URL = "https://github.com/player-ui/player/releases/tag/1.2.3";

/** Minimal fake Auto that captures the afterRelease tap and log output. */
function makeFakeAuto() {
  const logs = [];
  let tapped;
  const auto = {
    git: { options: { owner: "player-ui", repo: "player" } },
    logger: {
      log: {
        info: (m) => logs.push(`INFO ${m}`),
        warn: (m) => logs.push(`WARN ${m}`),
      },
      verbose: { info: (m) => logs.push(`VERB ${m}`) },
    },
    hooks: {
      afterRelease: {
        tapPromise: (_name, fn) => {
          tapped = fn;
        },
      },
    },
  };
  return { auto, logs, run: (ctx) => tapped(ctx) };
}

/** A release ctx with an html_url response, as auto provides after publishing. */
function releaseCtx(overrides = {}) {
  return {
    newVersion: "1.2.3",
    releaseNotes: "#### Bug Fix\n- x",
    response: { data: { html_url: RELEASE_URL } },
    ...overrides,
  };
}

/** Git subcommands run inside the clone (the `git -C <dir> <sub>` calls), in order. */
function gitSubcommands() {
  return execPromise.mock.calls
    .filter(([cmd, args]) => cmd === "git" && args[0] === "-C")
    .map(([, args]) => args[2]);
}

function ghCall() {
  return execPromise.mock.calls.find(([cmd]) => cmd === "gh");
}

beforeEach(() => {
  execPromise.mockReset();
  execPromise.mockResolvedValue("");
});

describe("pure helpers", () => {
  test("isPrerelease detects the semver hyphen", () => {
    expect(isPrerelease("1.2.3")).toBe(false);
    expect(isPrerelease("1.2.3-next.0")).toBe(true);
  });

  test("branchForVersion: stable -> targetBranch, prerelease -> release line", () => {
    expect(branchForVersion("1.2.3", "main")).toBe("main");
    expect(branchForVersion("1.2.3-next.0", "main")).toBe("1.2.3");
  });

  test("sourceReference: html_url when present, else owner/repo", () => {
    expect(sourceReference(RELEASE_URL, "player-ui", "player")).toBe(
      RELEASE_URL,
    );
    expect(sourceReference(undefined, "player-ui", "player")).toBe(
      "player-ui/player",
    );
  });

  test("buildTagAnnotation notes the autogenerated source", () => {
    const msg = buildTagAnnotation(RELEASE_URL, "1.2.3");
    expect(msg).toContain(`autogenerated from ${RELEASE_URL}`);
    expect(msg).toContain("1.2.3");
  });

  test("buildReleaseNotes prepends attribution to source notes", () => {
    const notes = buildReleaseNotes(RELEASE_URL, "#### 🐛 Bug Fix\n- x");
    expect(notes).toContain(`autogenerated from ${RELEASE_URL}`);
    expect(notes).toContain("#### 🐛 Bug Fix\n- x");
  });

  test("buildReleaseNotes emits header only with no source notes", () => {
    expect(buildReleaseNotes(RELEASE_URL, "")).not.toContain("\n\n");
  });
});

describe("SpmReleasePlugin afterRelease", () => {
  test("stable: clones, unzips, commits, annotates tag, pushes, creates Release", async () => {
    const { auto, run } = makeFakeAuto();
    new SpmReleasePlugin(OPTIONS).apply(auto);

    await run(releaseCtx());

    expect(gitSubcommands()).toEqual([
      "checkout",
      "add",
      "commit",
      "tag",
      "push",
    ]);

    const clone = execPromise.mock.calls.find(
      ([cmd, args]) => cmd === "git" && args[0] === "clone",
    );
    expect(clone?.[1]).toContain(OPTIONS.targetRepoUrl);
    const checkout = execPromise.mock.calls.find(
      ([cmd, args]) => cmd === "git" && args.includes("checkout"),
    );
    expect(checkout?.[1]).toContain("main");

    const tag = execPromise.mock.calls.find(
      ([cmd, args]) => cmd === "git" && args.includes("tag"),
    );
    expect(tag?.[1]).toContain("-a");
    expect(tag?.[1].join(" ")).toContain(RELEASE_URL);

    const unzip = execPromise.mock.calls.find(([cmd]) => cmd === "unzip");
    expect(unzip?.[1]).toEqual(["-o", OPTIONS.zipPath, "-d", "publishRepo"]);

    const gh = ghCall();
    expect(gh?.[1].slice(0, 3)).toEqual(["release", "create", "1.2.3"]);
    expect(gh?.[1]).toContain(OPTIONS.targetRepo);
    expect(gh?.[1][gh[1].length - 1]).toContain("#### Bug Fix\n- x");
  });

  test("falls back to owner/repo when the release response has no html_url", async () => {
    const { auto, run } = makeFakeAuto();
    new SpmReleasePlugin(OPTIONS).apply(auto);

    await run(releaseCtx({ response: undefined }));

    const tag = execPromise.mock.calls.find(
      ([cmd, args]) => cmd === "git" && args.includes("tag"),
    );
    expect(tag?.[1].join(" ")).toContain("autogenerated from player-ui/player");
  });

  test("prerelease: pushes annotated tag on release-line branch, NO GitHub Release", async () => {
    const { auto, run } = makeFakeAuto();
    new SpmReleasePlugin(OPTIONS).apply(auto);

    await run(releaseCtx({ newVersion: "1.2.3-next.0" }));

    expect(gitSubcommands()).toContain("tag");
    expect(gitSubcommands()).toContain("push");

    const checkout = execPromise.mock.calls.find(
      ([cmd, args]) => cmd === "git" && args.includes("checkout"),
    );
    expect(checkout?.[1]).toContain("1.2.3");

    expect(ghCall()).toBeUndefined();
  });

  test("skips (and warns) when required options are missing", async () => {
    const { auto, logs, run } = makeFakeAuto();
    new SpmReleasePlugin({ targetRepo: "x" }).apply(auto);

    await run(releaseCtx());

    expect(execPromise).not.toHaveBeenCalled();
    expect(logs.some((l) => l.startsWith("WARN"))).toBe(true);
  });

  test("skips when no version was released", async () => {
    const { auto, run } = makeFakeAuto();
    new SpmReleasePlugin(OPTIONS).apply(auto);

    await run(releaseCtx({ newVersion: undefined }));

    expect(execPromise).not.toHaveBeenCalled();
  });

  test("propagates a gh failure instead of swallowing it", async () => {
    // Fail only the `gh` call; git/unzip succeed.
    execPromise.mockImplementation(async (cmd) => {
      if (cmd === "gh")
        throw new Error("HTTP 422: Release.tag_name already exists");
      return "";
    });
    const { auto, run } = makeFakeAuto();
    new SpmReleasePlugin(OPTIONS).apply(auto);

    await expect(run(releaseCtx())).rejects.toThrow("already exists");
  });
});
