load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

kt_asset_test(
    name = "input_test",
    srcs = ["InputTest.kt"],
    test_class = "com.intuit.playerui.android.reference.assets.input.InputTest",
)
