load("//plugins:build.bzl", "kt_player_plugin")
load(":deps.bzl", "main_deps", "main_exports")

kt_player_plugin(
    name = "set-time-out",
    main_deps = main_deps,
    main_exports = main_exports,
    test_package = "com.intuit.player.plugins.settimeout",
)
