# load("//plugins:build.bzl", "kt_player_plugin")
# load(":deps.bzl", "main_deps", "main_exports", "main_resources")

# kt_player_plugin(
#     name = "beacon",
#     main_deps = main_deps,
#     main_exports = main_exports,
#     main_resources = main_resources,
#     test_package = "com.intuit.player.plugins.beacon",
# )
