import { Auto, IPlugin, execPromise } from "@auto-it/core";

/** Options for the SPM release plugin. */
export interface SpmReleasePluginOptions {
  /** SSH git URL to clone/push to, e.g. `git@github.com:player-ui/playerui-swift-package.git`. */
  targetRepoUrl: string;

  /** `owner/name` of the swift package repo for `gh`, e.g. `player-ui/playerui-swift-package`. */
  targetRepo: string;

  /** Path to the built package zip. */
  zipPath: string;

  /** Branch to push stable releases to. Defaults to `main`. */
  targetBranch?: string;
}

/** Whether a version is a prerelease/canary (carries a semver hyphen). */
export function isPrerelease(version: string): boolean {
  return version.includes("-");
}

/** Stable releases go to `targetBranch`; prereleases to their release line. */
export function branchForVersion(
  version: string,
  targetBranch: string,
): string {
  return isPrerelease(version) ? version.split("-")[0] : targetBranch;
}

/**
 * How the source release is referenced in the notes: the release's html_url
 * link when auto provides it, otherwise the plain `owner/repo`.
 */
export function sourceReference(
  htmlUrl: string | undefined,
  owner: string,
  repo: string,
): string {
  return htmlUrl || `${owner}/${repo}`;
}

/** Note written into every tag, linking back to the source release. */
export function buildTagAnnotation(sourceRef: string, version: string): string {
  return `Version ${version} — autogenerated from ${sourceRef}`;
}

/** GitHub Release body: attribution header plus the source release notes. */
export function buildReleaseNotes(
  sourceRef: string,
  releaseNotes: string | undefined,
): string {
  const header = `This release is autogenerated from ${sourceRef}`;
  const body = (releaseNotes || "").trim();
  return body ? `${header}\n\n${body}` : header;
}

/**
 * Publishes the iOS Swift Package by pushing the built zip to the package repo
 * as a tagged commit, and a GitHub Release (with source notes) for stable versions.
 */
export default class SpmReleasePlugin implements IPlugin {
  name = "spm-release";

  private readonly options: Partial<SpmReleasePluginOptions>;

  constructor(options: Partial<SpmReleasePluginOptions> = {}) {
    this.options = options;
  }

  apply(auto: Auto): void {
    // Runs after the source release exists so its notes are available to copy.
    auto.hooks.afterRelease.tapPromise(
      this.name,
      async ({ newVersion, releaseNotes, response }) => {
        const { targetRepoUrl, targetRepo, zipPath } = this.options;
        if (!targetRepoUrl || !targetRepo || !zipPath) {
          auto.logger.log.warn(
            `${this.name}: targetRepoUrl, targetRepo, and zipPath are required; skipping.`,
          );
          return;
        }
        if (!newVersion) {
          auto.logger.verbose.info(
            `${this.name}: no version released; skipping.`,
          );
          return;
        }

        // Reference the source release by its html_url, falling back to owner/repo.
        const { owner, repo } = auto.git!.options;
        const release = Array.isArray(response) ? response[0] : response;
        const sourceRef = sourceReference(release?.data.html_url, owner, repo);

        const branch = branchForVersion(
          newVersion,
          this.options.targetBranch ?? "main",
        );
        const workDir = "publishRepo";

        auto.logger.log.info(
          `${this.name}: publishing ${newVersion} to ${targetRepo} (branch ${branch})`,
        );

        // Fresh clone each run; CI reuse can leave a stale directory behind.
        await execPromise("rm", ["-rf", workDir]);
        await execPromise("git", ["clone", targetRepoUrl, workDir]);

        const git = (args: string[]) =>
          execPromise("git", ["-C", workDir, ...args]);

        await git(["checkout", "-B", branch]);
        await execPromise("unzip", ["-o", zipPath, "-d", workDir]);
        await git(["add", "."]);
        await git(["commit", "-m", `Version ${newVersion}`]);
        await git([
          "tag",
          "-a",
          newVersion,
          "-m",
          buildTagAnnotation(sourceRef, newVersion),
        ]);
        await git([
          "push",
          "-f",
          "--follow-tags",
          "origin",
          `refs/heads/${branch}:refs/heads/${branch}`,
        ]);

        // Prereleases carry their attribution in the tag; only stable versions
        // get a GitHub Release with the copied notes.
        if (isPrerelease(newVersion)) {
          auto.logger.verbose.info(
            `${this.name}: ${newVersion} is a prerelease; skipping GitHub Release.`,
          );
          return;
        }

        auto.logger.log.info(
          `${this.name}: creating GitHub Release ${newVersion} on ${targetRepo}`,
        );
        await execPromise("gh", [
          "release",
          "create",
          newVersion,
          "--repo",
          targetRepo,
          "--title",
          newVersion,
          "--notes",
          buildReleaseNotes(sourceRef, releaseNotes),
        ]);
      },
    );
  }
}
