load("//tools/ios:util.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "ReproPlugin",
    resources = [],
    deps = [
        "//ios/swiftui:PlayerUISwiftUI",
        "//plugins/repro/ios:PlayerUIBaseReproPlugin"
    ]
)

