load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/asset-testing-library",
    dependencies = [
        "//core/player:@player-ui/player",
        "//core/make-flow:@player-ui/make-flow",
        "//plugins/asset-transform/core:@player-ui/asset-transform-plugin",
    ],
)
