load("//plugins:defs.bzl", "kt_player_plugin")

main_exports = [
    "//jvm/core",
]

main_deps = main_exports


kt_player_plugin(
    name = "pending-transaction",
    main_deps = main_deps,
    main_exports = main_exports,
    test_package = "com.intuit.playerui.plugins.transactions",
)
