load("//android/player:build.bzl", "kt_player_test")

kt_player_test(
    name = "registry-plugin-tests",
    srcs = [
        "RegistryPluginTest.kt",
        "//android/player/src/test/java/com/intuit/playerui/android/renderer:BaseRenderableAssetTest.kt",
        "//android/player/src/test/java/com/intuit/playerui/android/extensions:CoroutineTestDispatcherExtension.kt"
    ]
)
