load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//android/player:deps.bzl", "test_deps")

kt_jvm_library(
    name = "android_utils_stub",
    srcs = ["Log.kt"],
    deps = ["//android/player:player"],
    visibility = ["//visibility:public"]
)
