load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/expressions",
    dependencies = [
        "//core/binding:@player-ui/binding",
        "//core/data:@player-ui/data",
        "//core/string-resolver:@player-ui/string-resolver",
        "//core/types:@player-ui/types",
        "//core/logger:@player-ui/logger",
        "@npm//tapable-ts",
    ],
)
