load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/validator",
    dependencies = [
        "//core/binding:@player-ui/binding",
        "//core/constants:@player-ui/constants",
        "//core/data:@player-ui/data",
        "//core/expressions:@player-ui/expressions",
        "//core/logger:@player-ui/logger",
        "//core/types:@player-ui/types",
        "@npm//tapable-ts",
        "@npm//timm",
    ],
    test_data = [
    ],
)
