# load("//plugins:build.bzl", "kt_player_plugin")
# load(":deps.bzl", "main_deps", "main_exports", "test_deps")

# kt_player_plugin(
#     name = "slf4j-logger",
#     main_deps = main_deps,
#     main_exports = main_exports,
#     test_deps = test_deps,
#     test_package = "com.intuit.player.jvm.plugins.logging.slf4j",
# )
