# load("//plugins:build.bzl", "kt_player_plugin_wrapper")

# kt_player_plugin_wrapper(
#     name = "reference-assets",
#     package_scope = "assets",
#     plugin_name = "ReferenceAssetsPlugin",
#     plugin_source = "plugins/reference-assets/core/dist/reference-assets-plugin.prod.js",
#     resources = "//plugins/reference-assets/core:ReferenceAssetsPlugin_Bundles",
# )
