load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/binding-grammar",
    dependencies = [
        "@npm//@types/parsimmon",
        "@npm//arr-flatten",
        "@npm//ebnf",
        "@npm//parsimmon",
    ],
)
