cc_binary(
    name = "hermes_hello",
    srcs = ["com_intuit_playerui_hermes_bridge_runtime_HermesRuntimeImpl.cpp"],
    deps = ["@hermes//:hermes_osx"],
)

cc_library(
    name = "hermes_jni",
    srcs = [
        "com_intuit_playerui_hermes_bridge_runtime_HermesRuntimeImpl.cpp",
        "com_intuit_playerui_hermes_bridge_runtime_HermesRuntimeImpl.h",
    ],
    deps = [],
)
