cc_library(
    name = "hermes_jni",
    srcs = [
        "com_intuit_playerui_hermes_bridge_runtime_HermesRuntimeImpl.cpp",
        "com_intuit_playerui_hermes_bridge_runtime_HermesRuntimeImpl.h",
    ],
    deps = [],
)
