load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/console-logger-plugin",
    dependencies = [
    ],
    peer_dependencies = [
        "//core/player:@player-ui/player",
    ],
)
