load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/partial-match-registry",
    dependencies = [
        "@npm//dlv",
        "@npm//@types/dlv",
        "@npm//sorted-array",
    ],
    library_name = 'Registry'
)
