# load("//plugins/reference-assets/android:build.bzl", "kt_asset_test")

# kt_asset_test(
#     name = "input_test",
#     srcs = ["InputTest.kt"],
#     test_class = "com.intuit.player.android.reference.assets.input.InputTest"
# )
