use_frameworks!
platform :ios, '13.0'
source 'https://cdn.cocoapods.org'

target 'PlayerUI_Example' do
  pod 'SwiftLint', '0.42.0'

  # Main
  pod 'PlayerUI', :path => '../', :appspecs => ['Demo'], :testspecs => ['Unit', 'ViewInspectorTests', 'XCUITests']

  # Packages
  pod 'PlayerUI/Core', :path => '../'
  pod 'PlayerUI/TestUtilitiesCore', :path => '../'
  pod 'PlayerUI/TestUtilities', :path => '../'
  pod 'PlayerUI/ReferenceAssets', :path => '../'
  pod 'PlayerUI/SwiftUI', :path => '../'
  pod 'PlayerUI/Logger', :path => '../'

  # Plugins
  pod 'PlayerUI/BeaconPlugin', :path => '../'
  pod 'PlayerUI/CheckPathPlugin', :path => '../'
  pod 'PlayerUI/CommonTypesPlugin', :path => '../'
  pod 'PlayerUI/CommonExpressionsPlugin', :path => '../'
  pod 'PlayerUI/ExpressionPlugin', :path => '../'
  pod 'PlayerUI/ExternalActionPlugin', :path => '../'
  pod 'PlayerUI/ExternalActionViewModifierPlugin', :path => '../'
  pod 'PlayerUI/MetricsPlugin', :path => '../'
  pod 'PlayerUI/PrintLoggerPlugin', :path => '../'
  pod 'PlayerUI/PubSubPlugin', :path => '../'
  pod 'PlayerUI/StageRevertDataPlugin', :path => '../'
  pod 'PlayerUI/SwiftUICheckPathPlugin', :path => '../'
  pod 'PlayerUI/TransitionPlugin', :path => '../'
  pod 'PlayerUI/TypesProviderPlugin', :path => '../'
  
  target 'PlayerUI_Tests' do
    inherit! :search_paths
  end
  target 'PlayerUI_ExampleUITests' do
    pod 'EyesXCUI'
  end
end

plugin 'cocoapods-resource-bundle-copier', {
  'bazelCommand' => 'bazel shutdown && bazel',
  'resource_map' => {
    # Core
    "PlayerUI/PlayerUI" => {
      'targets' => [
        {
         'target' => "//core/player:Player_Bundles_bundle_prod",
         'files' => ['player.prod.js']
        },
        {
         'target' => "//plugins/partial-match-fingerprint/core:PartialMatchFingerprintPlugin_Bundles_bundle_prod",
         'files' => ['partial-match-fingerprint-plugin.prod.js']
        },
        {
         'target' => "//core/partial-match-registry:Registry_Bundles_bundle_prod",
         'files' => ['partial-match-registry.prod.js']
        },
      ]
    },
    "PlayerUI/TestUtilities" => {'target' => "//core/make-flow:MakeFlow_Bundles_bundle_prod", 'files' => ['make-flow.prod.js']},
    "PlayerUI/ReferenceAssets" => {'target' => "//plugins/reference-assets/core:ReferenceAssetsPlugin_Bundles_bundle_prod", 'files' => ['reference-assets-plugin.prod.js']},

    # Plugins
    "PlayerUI/BaseBeaconPlugin" => {'target' => "//plugins/beacon/core:BeaconPlugin_Bundles_bundle_prod", 'files' => ['beacon-plugin.prod.js']},
    "PlayerUI/CommonTypesPlugin" => {'target' => "//plugins/common-types/core:CommonTypesPlugin_Bundles_bundle_prod", 'files' => ['common-types-plugin.prod.js']},
    "PlayerUI/CheckPathPlugin" => {'target' => "//plugins/check-path/core:CheckPathPlugin_Bundles_bundle_prod", 'files' => ['check-path-plugin.prod.js']},
    "PlayerUI/CommonExpressionsPlugin" => {'target' => "//plugins/common-expressions/core:CommonExpressionsPlugin_Bundles_bundle_prod", 'files' => ['common-expressions-plugin.prod.js']},
    "PlayerUI/ExpressionPlugin" => {'target' => "//plugins/expression/core:ExpressionPlugin_Bundles_bundle_prod", 'files' => ['expression-plugin.prod.js']},
    "PlayerUI/ExternalActionPlugin" => {'target' => "//plugins/external-action/core:ExternalActionPlugin_Bundles_bundle_prod", 'files' => ['external-action-plugin.prod.js']},
    "PlayerUI/MetricsPlugin" => {'target' => "//plugins/metrics/core:MetricsPlugin_Bundles_bundle_prod", 'files' => ['metrics-plugin.prod.js']},
    "PlayerUI/PubSubPlugin" => {'target' => "//plugins/pubsub/core:PubSubPlugin_Bundles_bundle_prod", 'files' => ['pubsub-plugin.prod.js']},
    "PlayerUI/TypesProviderPlugin" => {'target' => "//plugins/types-provider/core:TypesProviderPlugin_Bundles_bundle_prod", 'files' => ['types-provider-plugin.prod.js']},
    "PlayerUI/StageRevertDataPlugin" => {'target' => "//plugins/stage-revert-data/core:StageRevertDataPlugin_Bundles_bundle_prod", 'files' => ['stage-revert-data-plugin.prod.js']},
  }
}

plugin 'cocoapods-bazel', {
  rules: {
    'apple_framework' => { load: '@build_bazel_rules_ios//rules:framework.bzl', rule: 'apple_framework' }.freeze,
    'ios_application' => { load: '@build_bazel_rules_ios//rules:app.bzl', rule: 'ios_application' }.freeze,
    'ios_unit_test' => { load: '@build_bazel_rules_ios//rules:test.bzl', rule: 'ios_unit_test' }.freeze,
    'ios_ui_test' => { load: '@build_bazel_rules_ios//rules:test.bzl', rule: 'ios_ui_test' }.freeze
  }.freeze,
  features: {
    external_repository: true,
    generate_macro: true
  }
}
