# load("//plugins:defs.bzl", "kt_player_plugin")
# load(":deps.bzl", "main_deps", "main_exports", "main_resources")

# kt_player_plugin(
#     name = "expression",
#     main_deps = main_deps,
#     main_exports = main_exports,
#     main_resources = main_resources,
#     test_package = "com.intuit.playerui.plugins.expression",
# )
