# load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

# kt_asset_test(
#     name = "action_test",
#     srcs = ["ActionTest.kt"],
#     test_class = "com.intuit.playerui.android.reference.assets.action.ActionTest",
# )
