load("//plugins/reference-assets/android:build.bzl", "kt_asset_test")

kt_asset_test(
    name = "action_test",
    srcs = ["ActionTest.kt"],
    test_class = "com.intuit.player.android.reference.assets.action.ActionTest"
)
