load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

kt_asset_test(
    name = "text_test",
    srcs = ["TextTest.kt"],
    test_class = "com.intuit.playerui.android.reference.assets.text.TextTest",
)
