load("//plugins/reference-assets/android:defs.bzl", "kt_asset_test")

kt_asset_test(
    name = "info_test",
    srcs = ["InfoTest.kt"],
    test_class = "com.intuit.playerui.android.reference.assets.info.InfoTest",
)
