load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/make-flow",
    dependencies = [
        "//core/types:@player-ui/types",
    ],
    library_name = "MakeFlow"
)
