load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-ui/external-action-plugin",
    dependencies = [
    ],
    peer_dependencies = [
        "//core/player:@player-ui/player",
    ],
    library_name = "ExternalActionPlugin"
)
